# Site settings
author: Paul A. Fell-Cinoman
title: Paul Fell-Cinoman's Web Development Blog
header-img: img/home-bg.png
email: swellpf@gmail.com
copyright_name: Paul A. Fell-Cinoman
description: > # this means to ignore newlines until "baseurl:"
  Thoughts and Insights On My Tech Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SwellPF

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
