# Site settings
author: Paul A. Fell
title: Paul (Fell) Cinoman's Tech Blog
header-img: img/home-bg.png
email: swellpf@gmail.com
copyright_name: Paul A. Fell
description: > # this means to ignore newlines until "baseurl:"
  Introspections on Technology and Its Impact on Society
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SwellPF

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
